pipeline {
    agent any

    environment {
        DOCKER_IMAGE = "ahmedasar15/messaging_app:latest"
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main, master',
                    credentialsId: 'github-credentials',
                    url: 'https://github.com/ahmedasar00/alx-backend-python.git'
            }
        }

        stage('Install dependencies') {
            steps {
                sh '''
                    pip3 install --upgrade pip
                    pip3 install -r messaging_app/requirements.txt
                '''
            }
        }

        stage('Run Tests') {
            steps {
                sh '''
                    cd messaging_app
                    pytest --junitxml=report.xml
                '''
            }
        }

        stage('Publish Report') {
            steps {
                junit 'messaging_app/report.xml'
            }
        }

        stage('Build Docker Image') {
            steps {
                sh '''
                    cd messaging_app
                    docker build -t ${DOCKER_IMAGE} .
                '''
            }
        }

        stage('Push Docker Image') {
            steps {
                withCredentials([usernamePassword(
                    credentialsId: 'dockerhub-credentials',
                    usernameVariable: 'DOCKER_USERNAME',
                    passwordVariable: 'DOCKER_PASSWORD'
                )]) {
                    sh '''
                        echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
                        docker push ${DOCKER_IMAGE}
                    '''
                }
            }
        }
    }

    post {
        always { echo 'Pipeline Finished!' }
        success { echo 'All tests passed successfully' }
        failure { echo 'Some tests failed' }
    }
}
